### ISSUE TITLE
Error detected while processing C:\Users\devx\AppData\Local\nvim\plugin\packer_compiled.lua: &termguicolors must be set

### ISSUE THREAD

**Issue by caedencode** [slydragonn/dotfiles#2]
Hi I get this error whenever I try to use vim

**Comment by slydragonn** [comment]
Hi @criticalswateam1, that error is probably due to missing termguicolors options, I've updated the config, but if the same error occurs then I would appreciate it if you could tell me how to replicate the error.

**Comment by caedencode** [comment]
Hi @slydragonn  When did you update it and what files did you update? So I can review.

**Comment by caedencode** [comment]
> Hi @criticalswateam1, that error is probably due to missing termguicolors options, I've updated the config, but if the same error occurs then I would appreciate it if you could tell me how to replicate the error.
